import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/customized/navbar";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar>{children}</Navbar>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
